### ISSUE TITLE
Payment Type - Read

### ISSUE THREAD

**Issue by TimothyHarley** [partingpets/partingpets_fe#32]
## User Story
As a user when I access my profile I should be able to see an existing payment type

## Tech Notes
Add a table with payment types to the payment type section
Add a single payment type component
Add read call to paymentTypeRequests for Axios to back end

## Acceptance Criteria
When the user opens their profile page, they should be able to see the last 4 digits of each of their payment types

**Comment by MCrank** [comment]
Closed PR #52
